### ISSUE TITLE
Install chrome-app-livereload

### ISSUE THREAD

**Issue by franciscolourenco** [bestander/chrome-app-livereload#3]
How to install livereload.js?

In the example you use bower, but there are no instructions in the readme. 
Is this available on npm too?

**Comment by bestander** [comment]
Back when this component was created I used bower, see instructions here https://medium.com/@bestander_nz/live-reloading-chrome-apps-2a58d804c496#.r6dvinglf

Just put the livereload.js into a folder in your porject
