### ISSUE TITLE
Add chrome-app-livereload to npm

### ISSUE THREAD

**Issue by franciscolourenco** [bestander/chrome-app-livereload#4]

**Comment by bestander** [comment]
I just took livereload.js version 0.3.7, applied a simple patch and saved it here.
I won't be able to keep it in sync with livereload.js releases in npm.
Feel free to fork it and release it to npm on your own.
I'll be happy to link it from this repo and the blog post.

**Comment by franciscolourenco** [comment]
This live reload? Last release is 2.2.1?

https://github.com/livereload/livereload-js/releases

**Comment by bestander** [comment]
Should be this https://www.npmjs.com/package/tiny-lr

**Comment by franciscolourenco** [comment]
Isn't that just a server compatible with https://github.com/livereload/livereload-js ?

**Comment by bestander** [comment]
Yeah, I think it was coming with the client side too

**Comment by franciscolourenco** [comment]
Can't find the commit where you applied the patch. If you didn't version control that, could you share the patch? Thanks

**Comment by franciscolourenco** [comment]
Nevermind, found it. thanks
